spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sukima
    username: sukima
    password: sukima1234
    driver-class-name: org.postgresql.Driver

jwt:
  secret: rl6KfwPkI+JiVQimeA/XpWk6JwUlQpPqvVFta17h5t8=
  access-expiration: 900000
  refresh-expiration: 604800000
